name: Ruby specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    name: Ruby specs
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3', '3.4']
        channel: [stable]

        include:
          - ruby-version: 'ruby-head'
            channel: experimental

    continue-on-error: ${{ matrix.channel != 'stable' }}

    steps:
    - name: Install libmagic-dev
      run: |
        sudo apt-get update
        sudo apt-get -yq --no-install-suggests --no-install-recommends install libmagic-dev
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rspec
